print("Let's play Mad Libs for Homework 1\nType one word responses to the following:\n")
name = input("proper_name ==> ")
print(name)
adj1 = input("adjective ==> ")
print(adj1)
noun1 = input("noun ==> ")
print(noun1)
verb1 = input("verb ==> ")
print(verb1)
verb2 = input("verb ==> ")
print(verb2)
noun2 = input("noun ==> ")
print(noun2)
emotion1 = input("emotion ==> ")
print(emotion1)
verb3 = input("verb ==> ")
print(verb3)
noun3 = input("noun ==> ")
print(noun3)
season = input("season ==> ")
print(season)
adj2 = input("adjective ==> ")
print(adj2)
emotion2 = input("emotion ==> ")
print(emotion2)
teamname = input("team-name ==> ")
print(teamname)
noun4 = input("noun ==> ")
print(noun4)
adj3 = input("adjective ==> ")
print(adj3,"\n")
print("Here is your Mad Lib...\n")
print("Good morning ",name,"!\n",sep="")
print("  This will be a/an ",adj1," ",noun1,"! Are you ",verb1," forward to it?",sep="")
print("  You will ",verb2," a lot of ",noun2," and feel ",emotion1," when you do.",sep="")
print("  If you do not, you will ",verb3," this ",noun3,".\n",sep="")
print("  This ",season," was ",adj2,". Were you ",emotion2," when ",teamname," won",sep="")
print("  the ",noun4,"?\n",sep="")
print("  Have a/an ",adj3," day!",sep="")
